---
# tasks file for embedit.oracle-tools-flashback
- name: Create restore point '{{ restore_point_name }}'
  shell: . /etc/bashrc && echo "CREATE RESTORE POINT {{ restore_point_name }} GUARANTEE FLASHBACK DATABASE;" | sqlplus / as sysdba
  become: true
  become_user: oracle

